name: gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build dev
        run: |
          deno --version
          deno install --unstable --allow-read --allow-write --allow-net --allow-run -n pagic https://deno.land/x/pagic/mod.ts
          pagic build

      - name: Deploy dev
        uses: peaceiris/actions-dev@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ink-song.github.io
